module.exports={
    
    USER_COLLECTION:'user',
// ADMIN_COLLECTION:'datas'
CATEGORY_COLLECTION:'category',
PRODUCT_COLLECTION:'product',
CART_COLLECTION:'cart',
ORDER_COLLECTION:'order',
ADDRESS_COLLECTION :"Address",
BANNER_COLLECTION:"Banners",
COUPON_COLLECTION:"Coupons"
}
